[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/app/start.sh"
restartPolicyType = "on_failure"

[env]
PORT = { default = "8000" }
UPLOAD_DIR = "/app/uploads"
PYTHONPATH = "/app"